logging:
  level:
    ROOT: "INFO"

server:
  port: 8080

graphql:
  packages:
    - "com.khnumpottr.plantirrigationservice"
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000
